version: '3.1'
services:

  stats-server:
    build: explore-with-me/statsServer
    image: stats-server
    container_name: docker_stat_server
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/statsDb
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=admin


  stats-db:
    image: postgres:14-alpine
    container_name: docker_stats_Db
    ports:
      - "6543:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=statsDb



 # ewm-service: explorer-with-me-server.url
 #   build: ewm-main
 #   image: ewm-server
 #   container_name: docker_ewm_server
 #   ports:
  #    - "8080:8080"

  #ewm-db:
  #  image: postgres:14-alpine
  #  container_name: docker_ewm_Db
  #  ports:
  #    - "6543:5432"
  #  environment:
  #    - POSTGRES_USER=admin
   #   - POSTGRES_PASSWORD=admin
   #   - POSTGRES_DB=ewmDb
